# Generated by Django 6.0.6 on 2026-07-02 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_type', models.CharField(choices=[('STK', 'STK Push Callback'), ('C2B_VALIDATION', 'C2B Validation'), ('C2B_CONFIRMATION', 'C2B Confirmation'), ('B2C_RESULT', 'B2C Result'), ('B2C_TIMEOUT', 'B2C Timeout')], max_length=30)),
                ('source_ip', models.GenericIPAddressField(help_text='IP address from which the callback was received.')),
                ('raw_body', models.JSONField(help_text='Full deserialized request body, stored before any validation.')),
                ('related_transaction_id', models.UUIDField(blank=True, help_text='UUID of the related transaction, linked after processing.', null=True)),
                ('processed', models.BooleanField(default=False, help_text='True after the processing task completes successfully.')),
                ('error', models.TextField(blank=True, help_text='Error message if processing failed.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('C2B', 'C2B'), ('B2C', 'B2C'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, help_text='STK Push idempotency key (CheckoutRequestID from Daraja).', max_length=200, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, help_text='STK Push MerchantRequestID from Daraja.', max_length=200, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='B2C / Reversal idempotency key (ConversationID from Daraja).', max_length=200, null=True, unique=True)),
                ('originator_conversation_id', models.CharField(blank=True, help_text='B2C / Reversal OriginatorConversationID from Daraja.', max_length=200, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='Safaricom M-PESA receipt number. Populated only on SUCCESS.', max_length=50, null=True)),
                ('phone_number', models.CharField(help_text='Phone number in E.164 format: 2547XXXXXXXX.', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in KES.', max_digits=12)),
                ('account_reference', models.CharField(help_text='Account reference (max 12 chars per Daraja spec).', max_length=12)),
                ('transaction_desc', models.CharField(help_text='Transaction description (max 13 chars per Daraja spec).', max_length=13)),
                ('result_code', models.IntegerField(blank=True, help_text='Raw Safaricom result code from callback. 0 = success.', null=True)),
                ('result_desc', models.TextField(blank=True, help_text='Raw Safaricom result description from callback.', null=True)),
                ('raw_callback_payload', models.JSONField(blank=True, help_text='Full deserialized callback body for audit and debug.', null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='Set exactly once when the transaction reaches a terminal state.', null=True)),
                ('idempotency_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='testapp_mpe_status_ae1925_idx'), models.Index(fields=['phone_number'], name='testapp_mpe_phone_n_6dcff5_idx'), models.Index(fields=['initiated_at'], name='testapp_mpe_initiat_c92ad3_idx')],
            },
        ),
    ]
